import { describe, it, expect } from 'vitest';
import bcrypt from 'bcrypt';

describe('Bcrypt cross-platform compatibility', () => {
  // This hash was generated by Python bcrypt 4.x:
  //   uv run --with bcrypt python3 -c \
  //     "import bcrypt; print(bcrypt.hashpw(b'testpassword123', bcrypt.gensalt(12)).decode())"
  // Output: $2b$12$qr31iYHUYhv/HngLaSEgpePzhlT7HIfUmh32ZdoZ5eKLtS0Wl8Vgi
  const PYTHON_BCRYPT_HASH_2B =
    '$2b$12$qr31iYHUYhv/HngLaSEgpePzhlT7HIfUmh32ZdoZ5eKLtS0Wl8Vgi';
  const CORRECT_PASSWORD = 'testpassword123';
  const WRONG_PASSWORD = 'wrongpassword';

  it('verifies a Python-generated $2b$ hash with Node.js bcrypt', async () => {
    const result = await bcrypt.compare(CORRECT_PASSWORD, PYTHON_BCRYPT_HASH_2B);
    expect(result).toBe(true);
  });

  it('rejects wrong password against Python-generated $2b$ hash', async () => {
    const result = await bcrypt.compare(WRONG_PASSWORD, PYTHON_BCRYPT_HASH_2B);
    expect(result).toBe(false);
  });

  // Older Python bcrypt versions could produce $2a$ prefix
  // Node.js bcrypt handles both
  it('verifies a $2a$ prefix hash (older Python bcrypt)', async () => {
    // Same hash but with $2a$ prefix (functionally identical algorithm)
    const hash2a = PYTHON_BCRYPT_HASH_2B.replace('$2b$', '$2a$');
    const result = await bcrypt.compare(CORRECT_PASSWORD, hash2a);
    expect(result).toBe(true);
  });

  it('rejects wrong password against $2a$ prefix hash', async () => {
    const hash2a = PYTHON_BCRYPT_HASH_2B.replace('$2b$', '$2a$');
    const result = await bcrypt.compare(WRONG_PASSWORD, hash2a);
    expect(result).toBe(false);
  });

  it('can detect bcrypt hashes by prefix', () => {
    expect(PYTHON_BCRYPT_HASH_2B.startsWith('$2b$')).toBe(true);
    expect(PYTHON_BCRYPT_HASH_2B.replace('$2b$', '$2a$').startsWith('$2a$')).toBe(true);
  });
});
