// @vitest-environment jsdom
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it, vi } from 'vitest';

vi.mock('react-native', () => ({ Platform: { OS: 'web' } }));

const { ANSARI_MARK_SHAPES, ANSARI_MARK_VIEWBOX } =
  await import('./ansariMark');

const PUBLIC = path.resolve(__dirname, '../public');
const svgSource = readFileSync(path.join(PUBLIC, 'favicon.svg'), 'utf8');
const svg = new DOMParser().parseFromString(svgSource, 'image/svg+xml');
const head = new DOMParser().parseFromString(
  readFileSync(path.join(PUBLIC, 'index.html'), 'utf8'),
  'text/html',
).head;

/** Every `fill` the stylesheet sets, keyed by the media it applies under. */
function fills(css: string) {
  const dark = css.match(
    /@media\s*\(prefers-color-scheme:\s*dark\)\s*\{([\s\S]*?\})\s*\}/,
  );
  const fillOf = (block: string) =>
    [...block.matchAll(/path\s*\{\s*fill:\s*([^;\s]+);?\s*\}/g)].map(
      (m) => m[1],
    );
  return {
    base: fillOf(dark ? css.replace(dark[0], '') : css),
    dark: dark ? fillOf(dark[1]) : [],
  };
}

describe('the theme-adaptive SVG favicon', () => {
  it('parses as SVG', () => {
    expect(svg.querySelector('parsererror')).toBeNull();
    expect(svg.documentElement.nodeName).toBe('svg');
  });

  // Generated by `scripts/build-icons.mjs` from the mark's own constants;
  // a hand edit to either side that is not regenerated fails here.
  it('draws exactly the mark’s three pieces in its own viewBox', () => {
    expect(svg.documentElement.getAttribute('viewBox')).toBe(
      `0 0 ${ANSARI_MARK_VIEWBOX.width} ${ANSARI_MARK_VIEWBOX.height}`,
    );
    expect(
      Array.from(svg.querySelectorAll('path')).map((p) => p.getAttribute('d')),
    ).toEqual(ANSARI_MARK_SHAPES.map((shape) => shape.d));
  });

  it('inks the mark taupe-800 by default and taupe-200 in dark mode', () => {
    const css = svg.querySelector('style')?.textContent ?? '';
    expect(fills(css)).toEqual({ base: ['#2B2422'], dark: ['#E8E4E3'] });
  });

  // The ink is chosen only by the stylesheet, so nothing may pin a fill
  // the media query cannot reach, and nothing may paint a ground.
  it('leaves the ground transparent and the ink to the stylesheet', () => {
    expect(svg.querySelectorAll('rect, circle, image').length).toBe(0);
    expect(svg.querySelectorAll('[fill], [style]').length).toBe(0);
  });
});

describe('the favicon links', () => {
  const icons = Array.from(head.querySelectorAll('link[rel="icon"]')).map(
    (l) => ({
      href: l.getAttribute('href'),
      type: l.getAttribute('type'),
      sizes: l.getAttribute('sizes'),
    }),
  );

  it('offers the SVG as the scalable tab icon', () => {
    expect(icons).toContainEqual({
      href: '/favicon.svg',
      type: 'image/svg+xml',
      sizes: null,
    });
  });

  // Chrome ranks an `.ico` that claims `any`, or an exact 16 and 32,
  // above an SVG with no `sizes` and shows the `.ico` instead — checked
  // against Chrome's own favicon store for #230.
  it('keeps the raster fallbacks without letting the .ico outrank the SVG', () => {
    expect(icons).toContainEqual({
      href: '/favicon.ico',
      type: null,
      sizes: '32x32',
    });
    expect(icons.map((icon) => icon.href)).toContain('/icon-192.png');
    expect(
      head.querySelector('link[rel="apple-touch-icon"]')?.getAttribute('href'),
    ).toBe('/apple-touch-icon.png');
  });
});
