/**
 * The Terms of Service and the Privacy Policy, as the words a reader is
 * bound by (#241).
 *
 * This is legal text, not copy: every clause is reproduced exactly as
 * it was supplied, and `legal.test.ts` holds it to the source documents
 * in `__fixtures__` line for line. Change the wording only by changing
 * the fixture with it, and only on instruction.
 *
 * It is kept as data rather than written into the page's JSX so the
 * words live in one reviewable place, and so that test can read them
 * back. The shape is just enough to set the page: sections under a
 * heading, each a run of paragraphs and bulleted lists, and an inline
 * part where a span of text is a link.
 */

export const EFFECTIVE_DATE = '2026-10-06';
export const FEEDBACK_EMAIL = 'feedback@askansari.ai';

/** A span of a paragraph: plain words, an in-app link, or an address. */
export type LegalInline =
  | string
  | { kind: 'link'; href: '/privacy'; text: string }
  | { kind: 'email'; address: string };

export type LegalBlock =
  | { type: 'p'; parts: LegalInline[] }
  | { type: 'list'; items: LegalInline[][] };

export type LegalSection = { heading: string; blocks: LegalBlock[] };

export type LegalDoc = {
  title: string;
  effectiveDate: string;
  /** What comes between the date and the first heading. */
  preamble: LegalBlock[];
  sections: LegalSection[];
};

// The source sets two runs of terms ("Use of Ansari", "Account
// Registration") as bare consecutive lines, neither bulleted nor parted
// by blank lines. Each line is its own undertaking, so each is its own
// paragraph here: the author's breaks are kept, and no bullets are added
// that the source does not have.
//
// Where the Terms point to "our Privacy Policy", the source carries an
// editor's note in brackets asking for an in-app link; the note is an
// instruction, not a clause, so it is the link here and not the words.

export const TERMS: LegalDoc = {
  title: 'Ansari Terms of Service',
  effectiveDate: EFFECTIVE_DATE,
  preamble: [
    {
      type: 'p',
      parts: [
        'By accessing or using the Ansari digital assistant, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use Ansari.',
      ],
    },
  ],
  sections: [
    {
      heading: 'Nature of Service',
      blocks: [
        {
          type: 'p',
          parts: [
            "Ansari is an AI-powered digital assistant that provides educational and informational content about Islam. Ansari's responses are generated by artificial intelligence and are not a substitute for the guidance of qualified Islamic scholars, legal professionals, medical providers, licensed therapists, or other professionals. Users should consult qualified scholars for personal religious rulings and should not rely on Ansari as their sole source of religious guidance.",
          ],
        },
        {
          type: 'p',
          parts: [
            'Ansari is not a crisis service, mental health service, or emergency resource. If you are in crisis or experiencing a mental health emergency, please contact your local emergency services or a crisis helpline.',
          ],
        },
      ],
    },
    {
      heading: 'Use of Ansari',
      blocks: [
        {
          type: 'p',
          parts: [
            'You may use Ansari to ask questions about Islam and receive responses.',
          ],
        },
        {
          type: 'p',
          parts: ['You agree to use Ansari in a respectful and lawful manner.'],
        },
        {
          type: 'p',
          parts: [
            'You will not use Ansari to engage in any activity that is harmful, offensive, discriminatory, or otherwise unlawful.',
          ],
        },
        {
          type: 'p',
          parts: [
            'You will not use Ansari to misrepresent yourself or your identity.',
          ],
        },
        {
          type: 'p',
          parts: [
            'You will not use Ansari to generate content that is harmful, deceptive, or that violates applicable law.',
          ],
        },
      ],
    },
    {
      heading: 'Age Requirement',
      blocks: [
        {
          type: 'p',
          parts: ['You must be at least 18 years old to use Ansari.'],
        },
      ],
    },
    {
      heading: 'Account Registration',
      blocks: [
        {
          type: 'p',
          parts: [
            'You may create an account to access additional features of Ansari.',
          ],
        },
        {
          type: 'p',
          parts: [
            'You are responsible for maintaining the confidentiality of your account information.',
          ],
        },
        {
          type: 'p',
          parts: [
            'You are responsible for all activities that occur under your account.',
          ],
        },
      ],
    },
    {
      heading: 'Disclaimer of Warranties',
      blocks: [
        {
          type: 'p',
          parts: [
            'Ansari is provided on an "as is" and "as available" basis. We make no warranties of any kind, express or implied, as to the operation of Ansari or the accuracy of the information provided. We do not warrant that Ansari will be error-free or uninterrupted.',
          ],
        },
      ],
    },
    {
      heading: 'Limitation of Liability',
      blocks: [
        {
          type: 'p',
          parts: [
            'In no event shall Ansari Project LLC, its members, officers, employees, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or in connection with your use of or inability to use Ansari. To the fullest extent permitted by law, our total aggregate liability for all claims arising out of or relating to these Terms or your use of Ansari shall not exceed one hundred dollars (USD $100).',
          ],
        },
      ],
    },
    {
      heading: 'Indemnification',
      blocks: [
        {
          type: 'p',
          parts: [
            'You agree to indemnify and hold us harmless from any claims, losses, damages, liabilities, including legal fees and expenses, arising out of your use or misuse of Ansari.',
          ],
        },
      ],
    },
    {
      heading: 'Dispute Resolution',
      blocks: [
        {
          type: 'p',
          parts: [
            'Any dispute arising out of or relating to these Terms or your use of Ansari shall first be resolved through good-faith negotiation. If the dispute cannot be resolved through negotiation within thirty (30) days, it shall be resolved through binding arbitration administered in accordance with the rules of JAMS, conducted in California. You agree that any arbitration shall be conducted on an individual basis and not as a class, consolidated, or representative action.',
          ],
        },
      ],
    },
    {
      heading: 'Intellectual Property',
      blocks: [
        {
          type: 'p',
          parts: [
            "All rights, title, and interest in and to Ansari, including its underlying technology, models, and documentation, remain the property of Ansari Project LLC. Responses generated by Ansari are provided for your personal, non-commercial use. You may not reproduce, distribute, or create derivative works from Ansari's responses for commercial purposes without our prior written consent.",
          ],
        },
      ],
    },
    {
      heading: 'Termination',
      blocks: [
        {
          type: 'p',
          parts: [
            'We may terminate your access to Ansari in our sole discretion, without notice, for any violation of these Terms of Service.',
          ],
        },
      ],
    },
    {
      heading: 'Governing Law',
      blocks: [
        {
          type: 'p',
          parts: [
            'These Terms of Service shall be governed by and construed in accordance with the laws of California.',
          ],
        },
      ],
    },
    {
      heading: 'Privacy',
      blocks: [
        {
          type: 'p',
          parts: [
            'Your use of Ansari is also governed by our ',
            { kind: 'link', href: '/privacy', text: 'Privacy Policy' },
            ', which describes how we collect, use, and protect your information.',
          ],
        },
      ],
    },
    {
      heading: 'Severability',
      blocks: [
        {
          type: 'p',
          parts: [
            'If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary, and the remaining provisions shall remain in full force and effect.',
          ],
        },
      ],
    },
    {
      heading: 'Entire Agreement',
      blocks: [
        {
          type: 'p',
          parts: [
            'These Terms, together with our Privacy Policy, constitute the entire agreement between you and Ansari Project LLC regarding your use of Ansari and supersede any prior agreements.',
          ],
        },
      ],
    },
    {
      heading: 'Changes to Terms of Service',
      blocks: [
        {
          type: 'p',
          parts: [
            'We reserve the right to update these Terms of Service at any time. We will notify you of material changes by posting the updated Terms on this page and updating the effective date. Your continued use of Ansari after any changes constitutes acceptance of the revised Terms.',
          ],
        },
      ],
    },
    {
      heading: 'Contact Us',
      blocks: [
        {
          type: 'p',
          parts: [
            'If you have any questions about these Terms of Service, please contact us at ',
            { kind: 'email', address: FEEDBACK_EMAIL },
            '.',
          ],
        },
      ],
    },
  ],
};

export const PRIVACY: LegalDoc = {
  title: 'Ansari Privacy Policy',
  effectiveDate: EFFECTIVE_DATE,
  preamble: [
    {
      type: 'p',
      parts: [
        'This Privacy Policy describes how Ansari collects, uses, and discloses your information.',
      ],
    },
  ],
  sections: [
    {
      heading: 'Information We Collect',
      blocks: [
        { type: 'p', parts: ['Ansari collects information in two ways:'] },
        {
          type: 'list',
          items: [
            [
              'Guest Users: As a guest user, you can access Ansari without creating an account. We do not collect any personal information from guest users beyond basic analytics data (e.g., IP address, browser type) used to improve the service.',
            ],
            [
              'Registered Users: To create an account, you may be required to provide a username and email address. You may also choose to provide additional information in your profile, but this is entirely voluntary.',
            ],
          ],
        },
      ],
    },
    {
      heading: 'How We Use Automated Systems',
      blocks: [
        {
          type: 'p',
          parts: [
            'Ansari may use automated systems to provide safety resources and appropriate support within a session. These systems do not create records linked to your identity and are not used for user profiling or monitoring.',
          ],
        },
      ],
    },
    {
      heading: 'Use of Information',
      blocks: [
        {
          type: 'p',
          parts: [
            'We use the information we collect for the following purposes:',
          ],
        },
        {
          type: 'list',
          items: [
            [
              'Guest Users: We use analytics data to understand how guest users interact with Ansari and improve the overall user experience. We may also examine anonymized chat logs either manually or automatically to understand how users are interacting with the service. Chat logs reviewed for service improvement are not linked to individual user accounts.',
            ],
            [
              'Registered Users: We use your username to personalize your experience and your email address to communicate with you about important updates or information regarding Ansari. We will never share your email address with any third party without your consent. We may also examine anonymized chat logs either manually or automatically to understand how users are interacting with the service. Chat logs reviewed for service improvement are not linked to individual user accounts.',
            ],
          ],
        },
      ],
    },
    {
      heading: 'Disclosure of Information',
      blocks: [
        {
          type: 'p',
          parts: [
            'We will not disclose your information to any third party except in the following cases:',
          ],
        },
        {
          type: 'list',
          items: [
            [
              'Legal Requirements: We may disclose your information if required by law or to comply with a legal process.',
            ],
            [
              'Protecting Ansari and Others: We may disclose your information if we believe it is necessary to protect ourselves or others from harm.',
            ],
            ['Anonymized examples for presentation and research purposes.'],
            [
              "Additional web services: we may derive requests to other web services for retrieval augmentation (e.g. for Qur'an or Hadith search).",
            ],
            [
              'Safety resources: Ansari may display crisis helpline information or other safety resources during a session. If this involves a request to an external helpline directory, only a country code is transmitted. No user identifiers or conversation content are shared.',
            ],
          ],
        },
      ],
    },
    {
      heading: 'What We Do Not Do',
      blocks: [
        {
          type: 'p',
          parts: [
            'We do not link your queries to your account for the purpose of monitoring or profiling. We do not contact users based on the content of their queries. We do not create records that join user identity to the subject matter of conversations.',
          ],
        },
      ],
    },
    {
      heading: 'Data Retention',
      blocks: [
        {
          type: 'p',
          parts: [
            'We will retain your information for as long as your account is active or as needed to provide you with services. We will also retain and use your information to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our agreements.',
          ],
        },
      ],
    },
    {
      heading: 'Security',
      blocks: [
        {
          type: 'p',
          parts: [
            'We take reasonable steps to protect your information from unauthorized access, disclosure, alteration, or destruction. However, no internet transmission is completely secure, and we cannot guarantee the security of your information.',
          ],
        },
      ],
    },
    {
      heading: 'Your Choices',
      blocks: [
        {
          type: 'p',
          parts: ['You have the following choices regarding your information:'],
        },
        {
          type: 'list',
          items: [
            [
              'Access and Update: You can access and update your information in your account settings.',
            ],
            [
              'Deletion: You can delete your account at any time. Upon deletion of your account, we will delete your information, except for any information we are required to retain by law.',
            ],
            [
              'If you used a guest account and accidentally shared information, you can send a request to ',
              { kind: 'email', address: FEEDBACK_EMAIL },
              ' to request its removal.',
            ],
          ],
        },
      ],
    },
    {
      heading: "Children's Privacy",
      blocks: [
        {
          type: 'p',
          parts: [
            'Ansari is not intended for use by anyone under the age of 18. We do not knowingly collect personal information from users under 18. If you are a parent or guardian and you believe your child has provided us with personal information, please contact us. We will take steps to delete the information from our servers.',
          ],
        },
      ],
    },
    {
      heading: 'Changes to this Privacy Policy',
      blocks: [
        {
          type: 'p',
          parts: [
            'We may update this Privacy Policy from time to time. We will notify you of material changes by posting the updated Privacy Policy on this page and updating the effective date. Your continued use of Ansari after any changes constitutes acceptance of the revised Privacy Policy.',
          ],
        },
      ],
    },
    {
      heading: 'Contact Us',
      blocks: [
        {
          type: 'p',
          parts: [
            'If you have any questions about this Privacy Policy, please contact us at ',
            { kind: 'email', address: FEEDBACK_EMAIL },
            '.',
          ],
        },
      ],
    },
  ],
};
